name: Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12

      - name: Build React App
        run: |
          npm install # Install Dependencies
          CI=false npm run build # CI=false to ignore warnings

      - name: Install Surge
        run: npm install -g surge

      - name: Deploy to Surge
        run: surge ./build https://sen-cap-ip.surge.sh/ 38bcecc4c1966febd1b10e351764126c
